"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=['MainMenu.xib'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    packages=['clock_display_osx'],
    package_dir={'':'src'},
)
